### PR TITLE
added a check if JumpTo folder is owned (writable) by current user, typo fixes

### PR DESCRIPTION
**Pull request by Balestrino**
added a check if JumpTo folder is owned (writable) by current user
fix some typo errors

currently linuxcnc throws an error if JumpTo folder is not owned by current user:
* first error is on startup (but is ok, error in a popup)
* errors are show as python traceback dialog when going to a non owned folder and using "select previous file" 

Side note: changing the JumpTo directory does not write the changes into preferences file, so we have to close the gui in order to save it. Should we write the prefs file on the fly so changes are applied without restarting linuxcnc?
would be nice to implement USB drive quick access using JumpTo folder

### CODE REVIEW

**Comment by jepler** [comment]
I've called this pull request to the attention of the primary author of the file iconview.py and asked for his comment.

One small note:  Python provides 'os.access' to find out whether a location is writable.  This may be more efficient than creating a temporary file.
~~~~
>>> os.access("/tmp", os.W_OK)
True
>>> os.access("/etc", os.W_OK)
False
~~~~

**Comment by gmoccapy** [comment]
Hallo Balestrino,

I will check this until the weekend and try to merge it. I probally will change to the solution Jeff suggested.
I'll keep you informed.

Norbert

**Comment by Balestrino** [comment]
I tried with os.access("tmp", os.R_OK) without success but probably W_OK is the right way to test if a dir is accessible from current user.

Anyway Norbert what do you think about saving the JumpTo directory on-the-fly? that would be useful to set the JumpTo folder (ex. USB drives) without restarting LinuxCNC.
If you are agree i can modify that code

**Comment by gmoccapy** [comment]
Hallo Balestrino,

it is nearly done, but I do not understand the part:

            try:
-            new_path = self.model.get_path(new_iter)
+                new_iter = self.get_iter_last(self.model)
+                new_path = self.model.get_path(new_iter)
+            except:
+                return

Why you put a try in the except: part?
IMHO there should not be a problem, as we filter the error in the path part.

Saving the jump to dir is OK, but it should not be done in the widget itself, it should be done in the surrounding GUI, that is the way I do it in gmoccapy. (on_jump_to_dir_chooser_file_set())

Norbert

**Comment by Balestrino** [comment]
because if you enter a non owned folder and try to move with "Previous file" you get an error

**Comment by gmoccapy** [comment]
Balestrino,

i changed:
  def on_btn_jump_to_clicked(self,widget):
         if os.access(self.jump_to_dir, os.W_OK):
                self.cur_dir = self.jump_to_dir
                self._fill_store()
                self.btn_dir_up.set_sensitive(True)
        else:
               return False

Nothing else, I do not get an error, as the button jump_to will not change the dir, so IMHO if we get a not acceptable dir, we should deactivate the button.

Norbert

**Comment by gmoccapy** [comment]
I went on with my checks and even if I leave the file unchanged, i am not able to reproduce your error. I can set what ever folder I want using the settings page from gmoccapy, or also setting it as property.

No error at all!

Also write permisions are not needed, as we only read the content.

Could you please give more details?

Norbert

**Comment by Balestrino** [comment]
to reproduce the error go to the Load Program page and navigate to a non owned folder (ex: /root) and "Select previous file"

**Comment by gmoccapy** [comment]
Hallo Balestrino,

OK, now I got it! It is not caused by non owned folder! That is because there is no *.ngc file or folder in root! So when you push previous, the treeiter is None and that does cause the error!

I will fix that!

Norbert

**Comment by Balestrino** [comment]
Ok Norbert, i'll close this pull request
thank you

**Comment by gmoccapy** [comment]
OK, then you do agree with my fix?
I pushed it yesterday.

**Comment by jepler** [comment]
Thanks for your work on this issue, @Balestrino and @gmoccapy

**Comment by Balestrino** [comment]
@gmoccapy your fixes are ok. My was only a workaround.
great work Norbert, i love gmoccapy :+1:

**Pull request closed without merging**
